# Machine Learning modelling of the Car Claims dataset

In [26]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

plt.style.use('ggplot')

In [27]:
df = pd.read_csv('../data/carclaims.csv')

In [28]:
df.head()

,Serial No.,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,...,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange-Claim,NumberOfCars,Year,BasePolicy,FraudFound
0,1,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,...,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability,No
1,2,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,...,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision,No
2,3,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,...,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision,No
3,4,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,...,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability,No
4,5,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,...,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision,No

In [29]:
df.drop('Serial No.', axis=1, inplace=True)

In [30]:
df.head()

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange-Claim,NumberOfCars,Year,BasePolicy,FraudFound
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability,No
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision,No
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision,No
3,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,Married,...,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability,No
4,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision,No

In [31]:
df.shape

(15420, 33)

## Data Cleaning and Feature Engineering

In [32]:
df['Age_Group'] = pd.cut(df['Age'],bins=[0,9,19,29,39,49,59,69,79,89],labels=["0-9", "10-19","20-29","30-39","40-49","50-59", "60-69","70-79","80-89"])

In [33]:
df.columns

Index(['Month', 'WeekOfMonth', 'DayOfWeek', 'Make', 'AccidentArea',
       'DayOfWeekClaimed', 'MonthClaimed', 'WeekOfMonthClaimed', 'Sex',
       'MaritalStatus', 'Age', 'Fault', 'PolicyType', 'VehicleCategory',
       'VehiclePrice', 'PolicyNumber', 'RepNumber', 'Deductible',
       'DriverRating', 'Days:Policy-Accident', 'Days:Policy-Claim',
       'PastNumberOfClaims', 'AgeOfVehicle', 'AgeOfPolicyHolder',
       'PoliceReportFiled', 'WitnessPresent', 'AgentType',
       'NumberOfSuppliments', 'AddressChange-Claim', 'NumberOfCars', 'Year',
       'BasePolicy', 'FraudFound', 'Age_Group'],
      dtype='object')

In [34]:
df.drop(['WeekOfMonth', 'DayOfWeek', "Make", 'DayOfWeekClaimed', 'MonthClaimed', 'WeekOfMonthClaimed', 'PolicyNumber',
         'RepNumber', 'PastNumberOfClaims', 'DriverRating', 'Year'], inplace=True, axis=1)

In [35]:
df.columns

Index(['Month', 'AccidentArea', 'Sex', 'MaritalStatus', 'Age', 'Fault',
       'PolicyType', 'VehicleCategory', 'VehiclePrice', 'Deductible',
       'Days:Policy-Accident', 'Days:Policy-Claim', 'AgeOfVehicle',
       'AgeOfPolicyHolder', 'PoliceReportFiled', 'WitnessPresent', 'AgentType',
       'NumberOfSuppliments', 'AddressChange-Claim', 'NumberOfCars',
       'BasePolicy', 'FraudFound', 'Age_Group'],
      dtype='object')

In [36]:
df.head()

,Month,AccidentArea,Sex,MaritalStatus,Age,Fault,PolicyType,VehicleCategory,VehiclePrice,Deductible,...,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange-Claim,NumberOfCars,BasePolicy,FraudFound,Age_Group
0,Dec,Urban,Female,Single,21,Policy Holder,Sport - Liability,Sport,"more than 69,000",300,...,26 to 30,No,No,External,none,1 year,3 to 4,Liability,No,20-29
1,Jan,Urban,Male,Single,34,Policy Holder,Sport - Collision,Sport,"more than 69,000",400,...,31 to 35,Yes,No,External,none,no change,1 vehicle,Collision,No,30-39
2,Oct,Urban,Male,Married,47,Policy Holder,Sport - Collision,Sport,"more than 69,000",400,...,41 to 50,No,No,External,none,no change,1 vehicle,Collision,No,40-49
3,Jun,Rural,Male,Married,65,Third Party,Sedan - Liability,Sport,"20,000 to 29,000",400,...,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,Liability,No,60-69
4,Jan,Urban,Female,Single,27,Third Party,Sport - Collision,Sport,"more than 69,000",400,...,31 to 35,No,No,External,none,no change,1 vehicle,Collision,No,20-29

Month can be dropped since it does not affect out model. Also Vehicle category is already present in policy type, hence we can drop it as well. Similarily, base policy feature can also be removed.

In [37]:
df.drop(['Month', 'VehicleCategory', 'BasePolicy'], axis=1, inplace=True)

In [38]:
num_cols = df[['Age', 'Deductible']]
cat_cols = df.loc[:, ~df.columns.isin(['Age', 'Deductible'])]

In [39]:
num_cols.shape

(15420, 2)

In [40]:
cat_cols.shape

(15420, 18)

In [41]:
cat_cols.head()

,AccidentArea,Sex,MaritalStatus,Fault,PolicyType,VehiclePrice,Days:Policy-Accident,Days:Policy-Claim,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange-Claim,NumberOfCars,FraudFound,Age_Group
0,Urban,Female,Single,Policy Holder,Sport - Liability,"more than 69,000",more than 30,more than 30,3 years,26 to 30,No,No,External,none,1 year,3 to 4,No,20-29
1,Urban,Male,Single,Policy Holder,Sport - Collision,"more than 69,000",more than 30,more than 30,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,No,30-39
2,Urban,Male,Married,Policy Holder,Sport - Collision,"more than 69,000",more than 30,more than 30,7 years,41 to 50,No,No,External,none,no change,1 vehicle,No,40-49
3,Rural,Male,Married,Third Party,Sedan - Liability,"20,000 to 29,000",more than 30,more than 30,more than 7,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,No,60-69
4,Urban,Female,Single,Third Party,Sport - Collision,"more than 69,000",more than 30,more than 30,5 years,31 to 35,No,No,External,none,no change,1 vehicle,No,20-29

In [42]:
print(cat_cols['AccidentArea'].value_counts())
print(cat_cols['Sex'].value_counts())
print(cat_cols['PoliceReportFiled'].value_counts())
print(cat_cols['Fault'].value_counts())
print(cat_cols['WitnessPresent'].value_counts())
print(cat_cols['AgentType'].value_counts())
#

Urban    13822
Rural     1598
Name: AccidentArea, dtype: int64
Male      13000
Female     2420
Name: Sex, dtype: int64
No     14992
Yes      428
Name: PoliceReportFiled, dtype: int64
Policy Holder    11230
Third Party       4190
Name: Fault, dtype: int64
No     15333
Yes       87
Name: WitnessPresent, dtype: int64
External    15179
Internal      241
Name: AgentType, dtype: int64

In [43]:
# replacing 1 and 0 for above features
cat_cols['AccidentArea'] = cat_cols['AccidentArea'].map(dict(Urban=1, Rural=0))
cat_cols['Sex'] = cat_cols['Sex'].map(dict(Male=1, Female=0))
cat_cols['PoliceReportFiled'] = cat_cols['PoliceReportFiled'].map(dict(Yes=1, No=0))
cat_cols['WitnessPresent'] = cat_cols['WitnessPresent'].map(dict(Yes=1, No=0))

cat_cols['Fault'].replace(['Policy Holder', 'Third Party'],[1, 0], inplace=True)
cat_cols['AgentType'].replace(['External', 'Internal'],[1, 0], inplace=True)

C:\Users\nitee\AppData\Local\Temp\ipykernel_43000\1518854909.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_cols['AccidentArea'] = cat_cols['AccidentArea'].map(dict(Urban=1, Rural=0))
C:\Users\nitee\AppData\Local\Temp\ipykernel_43000\1518854909.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_cols['Sex'] = cat_cols['Sex'].map(dict(Male=1, Female=0))
C:\Users\nitee\AppData\Local\Temp\ipykernel_43000\1518854909.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_cols['PoliceReportFiled'] = cat_cols['PoliceReportFiled'].map(dict(Yes=1, No=0))
C:\Users\nitee\AppData\Local\Temp\ipykernel_43000\1518854909.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_cols['WitnessPresent'] = cat_cols['WitnessPresent'].map(dict(Yes=1, No=0))
C:\Users\nitee\AppData\Local\Temp\ipykernel_43000\1518854909.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_cols['Fault'].replace(['Policy Holder', 'Third Party'],[1, 0], inplace=True)
C:\Users\nitee\AppData\Local\Temp\ipykernel_43000\1518854909.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_cols['AgentType'].replace(['External', 'Internal'],[1, 0], inplace=True)

In [44]:
#AccidentArea, Sex, PoliceReportFiled, Fault, WitnessPresent, AgentType
print(cat_cols['AccidentArea'].value_counts())
print(cat_cols['Sex'].value_counts())
print(cat_cols['PoliceReportFiled'].value_counts())
print(cat_cols['Fault'].value_counts())
print(cat_cols['WitnessPresent'].value_counts())
print(cat_cols['AgentType'].value_counts())

1    13822
0     1598
Name: AccidentArea, dtype: int64
1    13000
0     2420
Name: Sex, dtype: int64
0    14992
1      428
Name: PoliceReportFiled, dtype: int64
1    11230
0     4190
Name: Fault, dtype: int64
0    15333
1       87
Name: WitnessPresent, dtype: int64
1    15179
0      241
Name: AgentType, dtype: int64

In [45]:
print(cat_cols['MaritalStatus'].value_counts())
print(cat_cols['PolicyType'].value_counts())
print(cat_cols['VehiclePrice'].value_counts())
print(cat_cols['Days:Policy-Accident'].value_counts())
print(cat_cols['Days:Policy-Claim'].value_counts())
print(cat_cols['AgeOfVehicle'].value_counts())
print(cat_cols['NumberOfSuppliments'].value_counts())
print(cat_cols['AddressChange-Claim'].value_counts())
#NumberOfCars
print(cat_cols['NumberOfCars'].value_counts())
# print(cat_cols['BasePolicy'].value_counts())
print(cat_cols['Age_Group'].value_counts())

Married     10625
Single       4684
Divorced       76
Widow          35
Name: MaritalStatus, dtype: int64
Sedan - Collision       5584
Sedan - Liability       4987
Sedan - All Perils      4087
Sport - Collision        348
Utility - All Perils     340
Utility - Collision       30
Sport - All Perils        22
Utility - Liability       21
Sport - Liability          1
Name: PolicyType, dtype: int64
20,000 to 29,000    8079
30,000 to 39,000    3533
more than 69,000    2164
less than 20,000    1096
40,000 to 59,000     461
60,000 to 69,000      87
Name: VehiclePrice, dtype: int64
more than 30    15247
none               55
8 to 15            55
15 to 30           49
1 to 7             14
Name: Days:Policy-Accident, dtype: int64
more than 30    15342
15 to 30           56
8 to 15            21
none                1
Name: Days:Policy-Claim, dtype: int64
7 years        5807
more than 7    3981
6 years        3448
5 years        1357
new             373
4 years         229
3 years         152
2 years          73
Name: AgeOfVehicle, dtype: int64
none           7047
more than 5    3867
1 to 2         2489
3 to 5         2017
Name: NumberOfSuppliments, dtype: int64
no change         14324
4 to 8 years        631
2 to 3 years        291
1 year              170
under 6 months        4
Name: AddressChange-Claim, dtype: int64
1 vehicle      14316
2 vehicles       709
3 to 4           372
5 to 8            21
more than 8        2
Name: NumberOfCars, dtype: int64
30-39    5041
40-49    3568
20-29    2828
50-59    2230
60-69     967
70-79     339
10-19      95
80-89      32
0-9         0
Name: Age_Group, dtype: int64

In [46]:
cat_dummies = pd.get_dummies(cat_cols[['MaritalStatus', 'PolicyType', 'VehiclePrice', 'Days:Policy-Accident', 'Days:Policy-Claim',
                        'AgeOfVehicle', 'NumberOfSuppliments', 'AddressChange-Claim', 'NumberOfCars', 'Age_Group']])

In [47]:
cat_dummies.shape

(15420, 59)

In [48]:
cat_dummies.head()

,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widow,PolicyType_Sedan - All Perils,PolicyType_Sedan - Collision,PolicyType_Sedan - Liability,PolicyType_Sport - All Perils,PolicyType_Sport - Collision,PolicyType_Sport - Liability,...,NumberOfCars_more than 8,Age_Group_0-9,Age_Group_10-19,Age_Group_20-29,Age_Group_30-39,Age_Group_40-49,Age_Group_50-59,Age_Group_60-69,Age_Group_70-79,Age_Group_80-89
0,0,0,1,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0

In [49]:
a = cat_cols[['AccidentArea', 'Sex', 'PoliceReportFiled', 'Fault', 'WitnessPresent', 'AgentType']]
cat_df = pd.concat([cat_dummies, a], axis=1)

In [50]:
cat_df.shape

(15420, 65)

In [51]:
main_df = pd.concat([cat_df, num_cols], axis=1)

In [52]:
main_df.shape

(15420, 67)

: